= Параллельная обработка сообщений

В системе {dv} реализован механизм, значительно ускоряющий рассылку почтовых уведомлений -- параллельная обработка групп сообщений. Функциональность требует установить Службу {ws} версии {prl-msg-ws-cu} и выше, {bo} версии {prl-msg-bo-cu} и выше. По умолчанию параллельная обработка отключена, её необходимо активировать вручную.

.Чтобы активировать параллельную обработку сообщений:
. Обновите Службу {ws} и {bo} до версии, поддерживающей данную функциональность.
. Дождитесь завершения обработки текущих сообщений, созданных до обновления (примерный срок завершения обработки составляет 1 неделю).
. В конфигурационном файле Службы {ws} измените настройку `MaxConcurrentMessagesPerGroup`, см. инструкцию в документации Службы {ws}: "xref:GBL-4806@workerservice:admin:parallel.adoc[]".
+
По умолчанию указано значение `1` -- одновременная обработка только 1 сообщения. Укажите желаемое значение.
+
Не указывайте слишком большие значения, чтобы избежать блокировки почтовых серверов. Начните с 5–10 потоков, параллельно отслеживая системные журналы на предмет возникновения ошибок подключения. При необходимости уменьшите значение.
